### ISSUE TITLE
WIN32 precompiled

### ISSUE THREAD

**Issue by The-Informaticist** [markmoraes/jove#14]
I can't find the precompiled Windows version mentioned in the README.win file. It mentioned a Windows 4.17 archive. Where can I find that?

**Comment by The-Informaticist** [comment]
Never mind ... I found the minGW version in the assets. I'm really new to Github. This version seems to work fine. I assume I put the jove.rc file under AppData/Roaming. Thanks for all your work. So nice to have my old Jove back.

**Comment by markmoraes** [comment]
Hmm, looking at the build, seems like the mingw version uses the Unix paths, so it has `/usr/local/lib/jove` and suchlike.  I should fix those to some more Windows-like path.  In the meantime, you can set the environment variable `JOVESHARE` to point to the `doc` subdirectory of wherever you unpacked the zip (or copied to, AppData/Roaming would be fine) and JOVELIB to either the directory that you unpacked the zip or some directory in AppData/Roaming where you copy the recover.exe binary (if you ever use `jove -r`, e.g. after a crash or powercycle of a machine, only very lightly tested)  Happy to see someone use the win32 binary after all this time!

**Comment by markmoraes** [comment]
Also, by default does seem to read `jove.rc` from wherever HOMEDRIVE and HOMEPATH are set to.

Looks like I should add code to check the Jove subdir in `%APPDATA%` (or `%USERPROFILE%\Appdata\Roaming` if unset) , `%LOCALAPPDATA%` (or `%USERPROFILE%\AppData\Local`  if unset ) and  (and stash the SHAREDIR,LIBDIR in `%PROGRAMDATA%\Jove\{share,lib}\` respectively )?

**Comment by The-Informaticist** [comment]
I'm setting up the environment variables per your first instructions now, and will test. As for the second message, I'm a Windows noob, so what you said sounds right, but don't take my word for it.

**Comment by The-Informaticist** [comment]
OK, I set the environment variables as you said (I just dumped everything in a folder in my home directory), but the startup help does not display, and the teachjove binary will not execute. When I try to use 'describe-command' I get the error message: Couldn't open "/usr/local/share/jove/cmds.doc" which means it's still looking for a Unix-style directory, I guess.

**Comment by markmoraes** [comment]
I unpacked https://github.com/jonmacs/jove/releases/download/4.17.4.9/jove-4.17.4.9-mingw.zip and then moved the resulting `jove-4.17.4.9-mingw` directory to `h:\bin\win3\jove` and tried the following on a Win10 Enterprise machine in a `cmd` window:
```
set JOVESHARE=h:\bin\win32\jove\doc
h:\bin\win32\jove\jove
```
and within that, `describe-command` worked fine.  I also tried
```
set JOVELIB=h:/bin/win32/jove
h:\bin\win32\jove\jove -r
```
(since the `jove` code seems agnostic to forward or backward slashes, it generally only uses forward slashes internally) which seems to work with
```
C:\Users\m\Downloads>h:\bin\win32\jove\jove.exe -r
Checking C:\Users\m\AppData\Local\Temp ...
Checking /var/lib/jove/preserve ...
There's nothing to recover.
```
But `teachjove`t failed because it invokes `cp` which it didn't find.  I'll look at that, should be easy to fix (famous last words)
```
cp: target 'C:\Users\m/teach-jove' is not a directory
teachjove: cannot execute "cp /usr/local/share/jove/teach-jove C:\Users\m/teach-jove; chmod 644 C:\Users\m/teach-jove"
````

**Comment by The-Informaticist** [comment]
Thanks so much. Everything seems to work great. I suppose I could open the teachjove file like any other file, and just never save changes. Cheers!

**Comment by markmoraes** [comment]
https://github.com/jonmacs/jove/releases/tag/4.17.5.0 should have working paths in the mingw release (and has both an i686 and an x86_64 version, both seem to work on my Windows testbeds -- 7, 10, 11).  A fix to how Jove handles relative paths for sharedir & libdir means that you can extract the zip anywhere and it sould work.  There's a new "ESC t" binding that should invoke the new Jove internal teach-jove command (or just ESC x teach-jove), plus the Debian style help window (which you can disable by setting JOVENOHELP=1 in your environment).  Appreciate any testing you can give it.
