### ISSUE TITLE
Clarify maintainer and recent history

### ISSUE THREAD

**Issue by peterjc** [markmoraes/jove#2]
My impression is you (Mark Moraes) have taken over from Hugh Redelmeier as project maintainer - at very least you had access to the traditional FTP site for Jove releases to update  http://ftp.cs.utoronto.ca/pub/moraes/jove/

Could you add something like the information in http://ftp.cs.utoronto.ca/pub/moraes/jove/jove.README to the README file here for clarity please?

It would also help to make it clear if http://ftp.cs.utoronto.ca/pub/moraes/jove/ (currently at v4.17.0.5) or GitHub (currently at v4.17.3.6 based on the latest tag) is the official source. This will be of interest to people doing jove packaging for Linux distributions etc.

**Comment by markmoraes** [comment]
Thanks.  I simplified ftp.cs.utoronto.ca/moraes/jove/jove.README and cleaned out the old versions from there.

I'll include some of that historical info in the current README as part of a long overdue cleanup/edit, coming up soon, I hope.
