### ISSUE TITLE
Compilation on 64bit Windows?

### ISSUE THREAD

**Issue by peterjc** [markmoraes/jove#4]
Clearly 32 bit Windows is/was supported, with ``README.w32`` talking about Windows/95 and Windows/NT.

Has jove been compiled under a 64 bit Windows?

(I may be missing something simple, but my initial attempts for conda-forge at https://github.com/conda-forge/staged-recipes/pull/13745 failed)

**Comment by markmoraes** [comment]
I can compile it on Win7 SP1 64bit on a Core i7-7500U using the VS2019 compiler, but it still uses -DWIN32.  The resulting binary does appear to run on a Win10 box, at least for a minimal test.

`F:\JOVE417S>nmake /f MAKEFILE.MSC

Microsoft (R) Program Maintenance Utility Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -DWIN32  -nologo -Ox -D_NDEBUG /c setmaps.c
setmaps.c
        cl /F 6000 setmaps.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:setmaps.exe
/stack:6000
setmaps.obj
        setmaps < keys.txt > keys.c
        cl -DWIN32  -nologo -Ox -D_NDEBUG -I. -c keys.c
keys.c
Making paths.h
        rc  -r jjove.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -DWIN32  -nologo -Ox -D_NDEBUG /c commands.c abbrev.c ask.c buf.c c.c
 case.c jctype.c delete.c extend.c argcount.c insert.c io.c jove.c macros.c mark
s.c misc.c mouse.c move.c para.c proc.c re.c reapp.c rec.c scandir.c list.c keym
aps.c util.c vars.c wind.c fmt.c disp.c term.c fp.c screen.c win32.c
commands.c
abbrev.c
ask.c
buf.c
c.c
case.c
jctype.c
delete.c
extend.c
argcount.c
insert.c
io.c
jove.c
macros.c
marks.c
misc.c
mouse.c
move.c
para.c
proc.c
Generating Code...
Compiling...
re.c
reapp.c
rec.c
scandir.c
list.c
keymaps.c
util.c
vars.c
wind.c
fmt.c
disp.c
term.c
fp.c
screen.c
win32.c
Generating Code...
        link  /OUT:jjove.exe /MAP /DEFAULTLIB:USER32 /DEFAULTLIB:KERNEL32 /DEFAU
LTLIB:COMDLG32 @jove.lnk /SUBSYSTEM:Console
Microsoft (R) Incremental Linker Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.

keys.obj
commands.obj
abbrev.obj
ask.obj
buf.obj
c.obj
case.obj
jctype.obj
delete.obj
extend.obj
argcount.obj
insert.obj
io.obj
jove.obj
macros.obj
marks.obj
misc.obj
mouse.obj
move.obj
para.obj
proc.obj
re.obj
reapp.obj
rec.obj
scandir.obj
list.obj
keymaps.obj
util.obj
vars.obj
wind.obj
fmt.obj
disp.obj
term.obj
fp.obj
screen.obj
win32.obj
setargv.obj
jjove.res
        cl -DWIN32  -nologo -Ox -D_NDEBUG /c recover.c
recover.c
        cl /F 6000 recover.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:recover.exe
/stack:6000
recover.obj
`

**Comment by peterjc** [comment]
Thanks - so this ought to be possible, and that output should be helpful in getting this to work via conda-forge.

**Comment by peterjc** [comment]
I see you are using ``Makefile.msc`` while I was trying ``Makefile.w32`` _[Ignore, I was confused - there was no ``Makefile.w32``]_

**Comment by markmoraes** [comment]
Did I miss something -- I don't see a Makefile.w32 in my current 4_17 branch (though that might be a more sensible name for Makefile.msc, which is somewhat historical;  it was once used for both w32 and dos back when MSVC worked for both).  I usually build for DOS and Windows by first generating jove417s.zip with 'make zip' and then unpacking that on the relevant VM to build with Makefile.msc (for Win 7 Pro) or Makefile.wat (in FreeDOS 12)

**Comment by peterjc** [comment]
Sorry, mixing stems and extensions. In this case README vs Makefile. My build attempt is failing before reaching the make command - likely something in the conda-forge Windows setup I am missing.

**Comment by peterjc** [comment]
Good news: jove for Linux and macOS is now available via conda.

Bad news: Windows support pending.

**Comment by markmoraes** [comment]
Peter, if you want to try commit 1417da64acb0ba9c8a0232d854f6d9b467c688cd from the 4_17 branch, it should cross-compile on Linux with mingw32 using the following invocation and the resulting executables appear to work on Windows.  Not yet tagged, but will be 4.17.3.8 once I get a bit more testing done (and perhaps 4.18.0.0 as a release, crossed fingers)  I've also tried to clean up the various README etc to describe Win32 builds.

make CC=i686-w64-mingw32-gcc SYSDEFS="-DMINGW" LOCALCC=gcc TERMCAPLIB= XEXT=.exe EXTRAOBJS="win32.o jjove.coff" EXTRALIBS=-lcomdlg32
