### ISSUE TITLE
Release tarballs vs github's smaller automatic ones

### ISSUE THREAD

**Issue by peterjc** [markmoraes/jove#5]
The following tar balls are different, first github's automatic snapshot of the the repository as of the tag:

https://github.com/jonmacs/jove/archive/4.17.3.6.tar.gz (478K)

And second, this which was uploaded as an asset to the release by the Jove maintainers:

https://github.com/jonmacs/jove/releases/download/4.17.3.6/jove-4.17.3.6.tgz (814K)

Looking at the list of files,

```
$ diff <(tar -tf 4.17.3.6.tar.gz | sort) <(tar -tf jove-4.17.3.6.tgz | sort)
2,3d1
< jove-4.17.3.6/ChangeLog
< jove-4.17.3.6/LICENSE
35a34
> jove-4.17.3.6/doc/cmds.doc
40a40,43
> jove-4.17.3.6/doc/jove.1
> jove-4.17.3.6/doc/jove.doc
> jove-4.17.3.6/doc/jove.man
> jove-4.17.3.6/doc/jove.man.ps
42a46
> jove-4.17.3.6/doc/jove.rc
51a56
> jove-4.17.3.6/doc/jovetool.1
62a68
> jove-4.17.3.6/doc/teachjove.1
84a91
> jove-4.17.3.6/jove.spec
107,110d113
< jove-4.17.3.6/old/
< jove-4.17.3.6/old/Makefile.bcc
< jove-4.17.3.6/old/Makefile.zor
< jove-4.17.3.6/old/sysdep.h
133a137
> jove-4.17.3.6/tags
```

Could you confirm that from the point of view of wanting to compile everything locally, they are interchangeable?

Is the missing larger ``jove-4.17.3.7.tgz`` and other assets on the 4.17.3.7 release (and some older releases) an oversight?

https://github.com/jonmacs/jove/releases/tag/4.17.3.7

vs:

https://github.com/jonmacs/jove/releases/tag/4.17.3.6
https://github.com/jonmacs/jove/releases/tag/4.17.2.7

(Asking from the perspective of automation, cross reference https://github.com/conda-forge/jove-feedstock/pull/3 )

**Comment by markmoraes** [comment]
Yes, the jove-VER.tgz are generated by me using 'make tgz' and added manually to the assets, so they contain a few generated output files to save from people needing groff, ctags to read the docs, allows jove to build as long as you have a compiler, includes and make, which most distros do.    It should be fine to build from the github-generated tarball (though I'll look at harmonizing the two).  ChangeLog and LICENSE should be in the github tar too, but old/ shouldn't, I'll update .gitattributes.  I should figure out how to get travis or git actions to make the other assets for me automatically...

**Comment by peterjc** [comment]
Great - so I'm fine building directly for the tagged commits in git for conda-forge. Thanks!

Do you want to keep this open for automating the asset upload? Or shall we close it?

**Comment by markmoraes** [comment]
Closing.  While I still intend to automate asset upload, and make some progress with github actions, no need to keep this open on that intention...
