### ISSUE TITLE
Handling "--" on the command line (Adam Sjøgren)

### ISSUE THREAD

**Issue by vixie** [markmoraes/jove#7]
Adam Sjøgren wrote on 2021-12-04 14:41:
> On a Debian (or Ubuntu) machine where I have configured jove (4.17.3.6)
> as the default editor, when I run "sudo visudo", jove pops up - but with
> an empty buffer and the message "Invalid switch --".
> What seems to be happening is that visudo calls "/usr/bin/editor --
> /etc/sudoers.tmp", and when /usr/bin/editor -> /etc/alternatives/editor
> -> /usr/bin/jove the error occurs.
> Would it be possible for jove to support the convention of "--" meaning
> "after this, there are no more switches, only file names"?
> Or at least accepting "--" as a valid [if ignored] switch?
> jove is so nicely suited for tasks like visudo.
>   Best regards,
>     Adam

**Comment by caseyleedom** [comment]
Seems like a reasonable ask.

**Comment by markmoraes** [comment]
Agreed, fixed, closing (will test and tag -- guess this is a good reminder to do the necessary testing to push a release out the door)

**Comment by C0RD** [comment]
don't forget tagging the release.

**Comment by markmoraes** [comment]
Will do, will find some time this week to figure out how/why my test infra has broken and fix it to test the release.  I also think there's a bug in 'recover' that I introduced in the last release (first recovered file works, but I think it doesn't clear pointers properly to the second file, ugh, so quite urgent I unbreak that problem.

**Comment by markmoraes** [comment]
Finally got the time to find/fix that recover bug, so I've tagged 4.17.4.0 with that fix (also finally got github actions working for test builds on various platforms)
